export default {
  nav: { home: "Home", upload: "Log", quests: "Quests", shop: "Shop", profile: "Profile" },
  dashboard: { title: "Dashboard", welcome: "Welcome", todayProgress: "Today's Progress", dailyQuests: "✅ Today's Quests", weeklyQuests: "📅 Weekly Quests", recentActivity: "Recent Activity", seeAll: "See all →", noActivity: "No activity yet", noActivitySub: "Start working out to earn your first coins", bmr: "BMR", bmi: "BMI", tdee: "TDEE", calories: "Calories", stats: "Stats", total: "Total", thisWeek: "This Week" },
  upload: { title: "📸 Log Activity", selectActivity: "Select Activity Type", photo: "📸 Photo Evidence", details: "Details", duration: "⏱️ Duration", distance: "📏 Distance", calories: "🔥 Calories", submit: "📸 Submit Evidence", verifying: "🤖 Verifying...", verifyingSub: "AI Agents are analyzing your evidence", result: "Logged successfully!", tryAgain: "🔄 Try Again", recordAgain: "📸 Log Again", notEnough: "Not Enough", buyNow: "Buy Now", fraudScore: "Fraud Score", riskLevel: "Risk Level", streakBonus: "Streak Bonus", questProgress: "📅 Quest Progress", verification: "🛡️ Verification", photos: "📸 Photos" },
  quests: { title: "📅 Quests", daily: "🌞 Daily", weekly: "📅 Weekly", claimed: "✅ Claimed", claim: "🎁 Claim Reward", inProgress: "🔒 In Progress" },
  shop: { title: "🛒 Shop", categories: { all: "✨ All", food: "🍕 Food", entertain: "🎮 Entertainment", rest: "😴 Rest", cosmetic: "💎 Cosmetics" }, owned: "✅ Owned", buy: "Buy", notEnough: "🪙 Not Enough", resetTomorrow: "Resets tomorrow", resetMonday: "Resets Monday" },
  profile: { title: "Profile", edit: "✏️ Edit Profile", name: "Name", bio: "Bio", weight: "⚖️ Weight (kg)", height: "📏 Height (cm)", save: "Save", cancel: "Cancel", clearData: "🗑️ Clear All Data", clearConfirm: "⚠️ This cannot be undone", clearPassword: "Password", clearPasswordHint: 'Use "fitquest"', stats: { collected: "🪙 Collected", workouts: "🏋️ Workouts", bestStreak: "🔥 Best Streak" }, calendar: "📊 Activity Calendar", recentActivity: "📸 Recent Activity", noHistory: "No history yet — start your first workout!", language: "🌐 Language", theme: "🎨 Theme" },
  auth: { login: "Connect with Google", logout: "🚪 Log out", welcome: "Welcome", setupTitle: "🏃 Welcome!", setupDesc: "Please enter your weight and height to calculate BMR and recommend calorie burn targets.", setupEditable: "Can be edited later in Profile", success: "✅ Saved" },
  error: { noBackend: "No backend on web", syncFailed: "Sync failed", failed: "❌ Verification failed", generic: "❌ An error occurred" },
  weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
}
