export default {
  nav: { home: "หน้าแรก", upload: "บันทึก", quests: "เควส", shop: "ร้านค้า", profile: "โปรไฟล์" },
  dashboard: { title: "แดชบอร์ด", welcome: "สวัสดี", todayProgress: "Progress วันนี้", dailyQuests: "✅ เควสวันนี้", weeklyQuests: "📅 เควสสัปดาห์", recentActivity: "กิจกรรมล่าสุด", seeAll: "ดูทั้งหมด →", noActivity: "ยังไม่มีกิจกรรม", noActivitySub: "เริ่มออกกำลังกายเพื่อรับเหรียญแรกของคุณ", bmr: "BMR", bmi: "BMI", tdee: "TDEE", calories: "Calories", stats: "สถิติ", total: "ทั้งหมด", thisWeek: "อาทิตย์นี้" },
  upload: { title: "📸 บันทึกกิจกรรม", selectActivity: "เลือกประเภทกิจกรรม", photo: "📸 หลักฐาน", details: "รายละเอียด", duration: "⏱️ ระยะเวลา", distance: "📏 ระยะทาง", calories: "🔥 แคลอรี", submit: "📸 ส่งหลักฐาน", verifying: "🤖 กำลังตรวจสอบ...", verifyingSub: "AI Agents กำลังวิเคราะห์หลักฐานของคุณ", result: "บันทึกสำเร็จ!", tryAgain: "🔄 ลองใหม่", recordAgain: "📸 บันทึกอีกครั้ง", notEnough: "ไม่พอ", buyNow: "ซื้อเลย", fraudScore: "Fraud Score", riskLevel: "Risk Level", streakBonus: "Streak Bonus", questProgress: "📅 ความคืบหน้าเควส", verification: "🛡️ การตรวจสอบ", photos: "📸 รูปภาพ" },
  quests: { title: "📅 เควส", daily: "🌞 รายวัน", weekly: "📅 รายสัปดาห์", claimed: "✅ รับแล้ว", claim: "🎁 รับรางวัล", inProgress: "🔒 กำลังทำ" },
  shop: { title: "🛒 ร้านค้า", categories: { all: "✨ ทั้งหมด", food: "🍕 อาหาร", entertain: "🎮 บันเทิง", rest: "😴 พักผ่อน", cosmetic: "💎 เครื่องประดับ" }, owned: "✅ มีแล้ว", buy: "ซื้อเลย", notEnough: "🪙 ไม่พอ", resetTomorrow: "รีเซ็ตพรุ่งนี้", resetMonday: "รีเซ็ตวันจันทร์" },
  profile: { title: "โปรไฟล์", edit: "✏️ แก้ไขโปรไฟล์", name: "ชื่อ", bio: "คำอธิบาย", weight: "⚖️ น้ำหนัก (กก.)", height: "📏 ส่วนสูง (ซม.)", save: "บันทึก", cancel: "ยกเลิก", clearData: "🗑️ ล้างข้อมูลทั้งหมด", clearConfirm: "⚠️ หากล้างข้อมูลแล้วจะไม่สามารถกู้คืนได้อีก", clearPassword: "รหัสผ่าน", clearPasswordHint: 'ใช้ "fitquest"', stats: { collected: "🪙 สะสม", workouts: "🏋️ ครั้ง", bestStreak: "🔥 สูงสุด" }, calendar: "📊 Activity Calendar", recentActivity: "📸 กิจกรรมล่าสุด", noHistory: "ยังไม่มีประวัติ — เริ่มออกกำลังกายครั้งแรก!", language: "🌐 ภาษา", theme: "🎨 Theme" },
  auth: { login: "เชื่อมต่อกับ Google", logout: "🚪 ออกจากระบบ", welcome: "ยินดีต้อนรับ", setupTitle: "🏃 ยินดีต้อนรับ!", setupDesc: "กรุณากรอกน้ำหนักและส่วนสูงของคุณ เพื่อคำนวณ BMR และแนะนำแคลอรีที่ควรเผาผลาญ", setupEditable: "แก้ไขภายหลังได้ที่หน้าโปรไฟล์", success: "✅ บันทึก" },
  error: { noBackend: "ไม่มี backend บน web", syncFailed: "ซิงก์ล้มเหลว", failed: "❌ ไม่ผ่านการตรวจสอบ", generic: "❌ เกิดข้อผิดพลาด" },
  weekdays: ["อา", "จ", "อ", "พ", "พฤ", "ศ", "ส"],
}
